### ISSUE TITLE
Doctors appointment days

### ISSUE THREAD

**Issue by kanilona91** [Mugerwa-Joseph/Hospital-Management-System#19]
**Days**
*Monday*
``Tuesday``
~~Wednesday~~
***Thursday***

QUOTING:
'''
Git status
Git add
Git commit
'''
LINKS
this site was built using [GitHub,Opensource 
](https://opensource.com/)
**Image**
![doctor.jpeg](url)

*LISTS*
1 John
2 Joseph
3 jeff

Task list
- [x] doctors
- [ ] nurses
- [ ] patience

@Mugerwa-Joseph 
@richarddushime 
@Nzamuyejoram

**Comment by Mugerwa-Joseph** [comment]
Hope you were practicing issues formatting.
Thanks.
